export const LOGIN_USER = 'LOGIN USER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';
export const SOCIAL_SIGNUP_SUCCESS = 'SOCIAL_SIGNUP_SUCCESS';
export const SOCIAL_SIGNUP_FAILURE = 'SOCIAL_SIGNUP_FAILURE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_HIDE_FLASH_MESSAGE = "SIGNUP_HIDE_FLASH_MESSAGE";
export const SOCIAL_LOGIN_FLASH_MESSAGE = "SOCIAL_LOGIN_FLASH_MESSAGE";
export const SOCIAL_CONNECT_SUCCESS = "SOCIAL_CONNECT_SUCCESS";
export const SOCIAL_CONNECT_FAILURE = "SOCIAL_CONNECT_FAILURE";

export const INIT_REQUEST = 'INIT_REQUEST';
export const INIT_SUCCESS = 'INIT_SUCCESS';
export const INIT_FAILURE = 'INIT_FAILURE';

//Get current user(me) from token in localStorage
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const RESET_TOKEN = 'RESET_TOKEN';
export const PASSWORD_RESET_LINK_SEND_SUCCESS = 'PASSWORD_RESET_LINK_SEND_SUCCESS';
export const PASSWORD_RESET_LINK_SEND_FAILURE = 'PASSWORD_RESET_LINK_SEND_FAILURE';
export const RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAILURE = 'RESET_PASSWORD_REQUEST_FAILURE';
export const RESET_PASSWORD_TOKEN_INFO_SUCCESS = 'RESET_PASSWORD_TOKEN_INFO_SUCCESS';
export const RESET_PASSWORD_TOKEN_INFO_FAILURE = 'RESET_PASSWORD_TOKEN_INFO_FAILURE';
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

//Static Data
export const USER_INTERESTS_SUCCESS = "USER_INTERESTS";
export const USER_INTERESTS_FAILURE = "USER_INTERESTS_FAILURE";
export const USER_REFS_SUCCESS = "USER_REFS_SUCCESS";
export const USER_REFS_FAILURE = "USER_REFS_FAILURE";

//categories
export const DEAL_CATEGORIES = "DEAL_CATEGORIES";
export const ADD_NEW_DEAL_CATEGORIES_FAILURE = "ADD_NEW_DEAL_CATEGORIES_FAILURE";
export const ADD_NEW_DEAL_CATEGORIES_SUCCESS = "ADD_NEW_DEAL_CATEGORIES_SUCCESS";

// users
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_FAILURE = 'SETUP_USER_FAILURE';
export const ACTIVATE_USER_REQUEST_SUCCESS = 'ACTIVATE_USER_REQUEST_SUCCESS';
export const ACTIVATE_USER_REQUEST_FAILURE = 'ACTIVATE_USER_REQUEST_FAILURE';
export const COUNTRIES_SUCCESS = "COUNTRIES_SUCCESS";
export const COUNTRIES_FAILURE = "COUNTRIES_FAILURE";
export const EMAIL_NOTIFICATION_SUCCESS = "EMAIL_NOTIFICATION_SUCCESS";
export const EMAIL_PREFERENCE_SUCCESS = "EMAIL_PREFERENCE_SUCCESS";
export const UPDATE_EMAIL_NOTIFICATION_SUCCESS = "UPDATE_EMAIL_NOTIFICATION_SUCCESS";
export const UPDATE_EMAIL_PREFERENCE_SUCCESS = "UPDATE_EMAIL_PREFERENCE_SUCCESS";
export const REQUEST_COMPANY_SUCCESS = "REQUEST_COMPANY_SUCCESS";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAILURE = "UPDATE_COMPANY_FAILURE";

export const HEADER_TRANSPERENCY = "HEADER_TRANSPERENCY";
