export const USER_LIST_FOR_CURRENT_ACCOUNT_SUCCESS = 'USER_LIST_FOR_CURRENT_ACCOUNT_SUCCESS';
export const UPDATE_PAGE_TITLE = 'UPDATE_PAGE_TITLE';

export const LOGIN_USER = 'LOGIN USER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const INIT_REQUEST = 'INIT_REQUEST';
export const INIT_SUCCESS = 'INIT_SUCCESS';
export const INIT_FAILURE = 'INIT_FAILURE';

//Get current user(me) from token in localStorage
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const RESET_TOKEN = 'RESET_TOKEN';
export const PASSWORD_RESET_LINK_SEND_SUCCESS = 'PASSWORD_RESET_LINK_SEND_SUCCESS';
export const PASSWORD_RESET_LINK_SEND_FAILURE = 'PASSWORD_RESET_LINK_SEND_FAILURE';
export const RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAILURE = 'RESET_PASSWORD_REQUEST_FAILURE';
export const USERS_HIDE_FLASH_MESSAGE = 'USERS_HIDE_FLASH_MESSAGE';

export const CLIENT_MODE_REQUEST = 'CLIENT_MODE_REQUEST';
export const CLIENT_MODE_SUCCESS = 'CLIENT_MODE_SUCCESS';
export const EXIT_CLIENT_MODE_SUCCESS = 'EXIT_CLIENT_MODE_SUCCESS';

//Project
export const PROJECTS_FETCH = 'PROJECTS_FETCH';
export const PROJECT_NOTES_CHANGE_FILTER = 'PROJECT_NOTES_CHANGE_FILTER';
export const PROJECT_STRATEGY_REQUEST = 'PROJECT_STRATEGY_REQUEST';
export const PROJECT_STRATEGY_SAVE = 'PROJECT_STRATEGY_SAVE';
export const PROJECT_SOURCE_COMPANY_UPDATE = 'PROJECT_SOURCE_COMPANY_UPDATE';
export const PROJECT_SOURCE_COMPANY_UPDATE_SUCCESS = 'PROJECT_SOURCE_COMPANY_UPDATE_SUCCESS';
export const PROJECT_SOURCE_COMPANY_UPDATE_FAILURE = 'PROJECT_SOURCE_COMPANY_UPDATE_FAILURE';
export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const PROJECT_LIST_FAILURE = 'PROJECT_LIST_FAILURE';

export const PROJECT_DETAIL_SUCCESS = 'PROJECT_DETAIL_SUCCESS';

export const PROJECT_POSITION_SUCCESS = 'PROJECT_POSITION_SUCCESS';
export const SAVE_PROJECT_POSITION = 'SAVE_PROJECT_POSITION';
export const SAVE_PROJECT_POSITION_SUCCESS = 'SAVE_PROJECT_POSITION_SUCCESS';
export const SAVE_PROJECT_POSITION_FAILURE = 'SAVE_PROJECT_POSITION_FAILURE';
export const PROJECTS_CHANGE_PAGE_NUMBER = 'PROJECTS_CHANGE_PAGE_NUMBER';
export const PROJECTS_CHANGE_SORT_BY = 'PROJECTS_CHANGE_SORT_BY';

export const PROJECT_SOURCE_COMPANIES_REQUEST = 'PROJECT_SOURCE_COMPANIES_REQUEST';
export const PROJECT_SOURCE_COMPANIES_SUCCESS = 'PROJECT_SOURCE_COMPANIES_SUCCESS';
export const PROJECT_SOURCE_COMPANIES_FAILURE = 'PROJECT_SOURCE_COMPANIES_FAILURE';

export const PROJECT_CANDIDACIES_REQUEST = 'PROJECT_CANDIDACIES_REQUEST';
export const PROJECT_CANDIDACIES_SUCCESS = 'PROJECT_CANDIDACIES_SUCCESS';
export const PROJECT_CANDIDACIES_FAILURE = 'PROJECT_CANDIDACIES_FAILURE';
export const CANDIDACIES_CHANGE_PAGE_NUMBER = 'CANDIDACIES_CHANGE_PAGE_NUMBER';
export const CANDIDACIES_CHANGE_SORT_BY = 'CANDIDACIES_CHANGE_SORT_BY';
export const CANDIDACIES_CHANGE_FILTER = 'CANDIDACIES_CHANGE_FILTER';
export const CANDIDACIES_HIDE_FLASH_MESSAGE = 'CANDIDACIES_HIDE_FLASH_MESSAGE';

export const PROJECT_NEW_REQUEST = 'PROJECT_NEW_REQUEST';
export const PROJECT_ADD_REQUEST_SUCCESS = 'PROJECT_ADD_REQUEST_SUCCESS';
export const PROJECT_ADD_REQUEST_FAILURE = 'PROJECT_ADD_REQUEST_FAILURE';
export const PROJECTS_CHANGE_FILTER = 'PROJECTS_CHANGE_FILTER';
export const PROJECT_CLIENT_LIST_SUCCESS = 'PROJECT_CLIENT_LIST_SUCCESS';
export const PROJECT_CLIENT_LIST_FAILURE = 'PROJECT_CLIENT_LIST_FAILURE';
export const BULK_PROJECT_DELETE_SUCCESS = 'BULK_PROJECT_DELETE_SUCCESS';
export const ADD_CLIENTS_TO_PROJECTS_SUCCESS = 'ADD_CLIENTS_TO_PROJECTS_SUCCESS';
export const ADD_CLIENTS_TO_PROJECTS_FAILURE = 'ADD_CLIENTS_TO_PROJECTS_FAILURE';
export const ADD_MEMBERS_TO_PROJECTS_SUCCESS = 'ADD_MEMBERS_TO_PROJECTS_SUCCESS';
export const ADD_MEMBERS_TO_PROJECTS_FAILURE = 'ADD_MEMBERS_TO_PROJECTS_FAILURE';
export const PROJECT_DISPLAY_SUCCESS = 'PROJECT_DISPLAY_SUCCESS';
export const PROJECT_USERS_SUCCESS = 'PROJECT_USERS_SUCCESS';
export const PROJECT_CLIENTS_SUCCESS = 'PROJECT_CLIENTS_SUCCESS';
export const ADD_PROJECT_CLIENT_SUCCESS = 'ADD_PROJECT_CLIENT_SUCCESS';
export const ADD_PROJECT_USER_SUCCESS = 'ADD_PROJECT_USER_SUCCESS';
export const PROJECT_USER_LIST_SUCCESS = 'PROJECT_USER_LIST_SUCCESS';
export const DELETE_PROJECT_CLIENT_SUCCESS = 'DELETE_PROJECT_CLIENT_SUCCESS';
export const DELETE_PROJECT_USER_SUCCESS = 'DELETE_PROJECT_USER_SUCCESS';
export const CANDIDACIES_BULK_UPDATE_SUCCESS = 'CANDIDACIES_BULK_UPDATE_SUCCESS';
export const CANDIDACIES_BULK_TASK_LIST_SUCCESS = 'CANDIDACIES_BULK_TASK_LIST_SUCCESS';
export const CANDIDACIES_BULK_ADD_PROJECT_SUCCESS = 'CANDIDACIES_BULK_ADD_PROJECT_SUCCESS';
export const PROJECTS_EXPORT_SUCCESS = 'PROJECTS_EXPORT_SUCCESS';
export const CANDIDATES_EXPORT_SUCCESS = 'CANDIDATES_EXPORT_SUCCESS';
export const PROJECT_ACTIVITIES_SUCCESS = 'PROJECT_ACTIVITIES_SUCCESS';
export const CANDIDATES_BULK_NOTE_ADD_SUCCESS = 'CANDIDATES_BULK_NOTE_ADD_SUCCESS';
export const UPDATE_PROJECT_SETTINGS_SUCCESS = 'UPDATE_PROJECT_SETTINGS_SUCCESS';
export const PROJECT_SPECIALTIES_SUCCESS = 'PROJECT_SPECIALTIES_SUCCESS';
export const PROJECT_INDUSTRIES_SUCCESS = 'PROJECT_INDUSTRIES_SUCCESS';
export const PROJECT_MEATADATA_SUCCESS = 'PROJECT_MEATADATA_SUCCESS';
export const PROJECT_INVESTORS_SUCCESS = 'PROJECT_INVESTORS_SUCCESS';
export const PROJECT_FEE_SUCCESS = 'PROJECT_FEE_SUCCESS';
export const PROJECT_TAGS_SUCCESS = 'PROJECT_TAGS_SUCCESS';
export const UPDATE_PROJECT_METADATA_SUCCESS = 'UPDATE_PROJECT_METADATA_SUCCESS';
export const ADD_PROJECT_SPECIALTY_SUCCESS = 'ADD_PROJECT_SPECIALTY_SUCCESS';
export const ADD_PROJECT_INDUSTRY_SUCCESS = 'ADD_PROJECT_INDUSTRY_SUCCESS';
export const ADD_PROJECT_INVESTOR_SUCCESS = 'ADD_PROJECT_INVESTOR_SUCCESS';
export const REMOVE_PROJECT_SPECIALTY_SUCCESS = 'REMOVE_PROJECT_SPECIALTY_SUCCESS';
export const REMOVE_PROJECT_INDUSTRY_SUCCESS = 'REMOVE_PROJECT_INDUSTRY_SUCCESS';
export const REMOVE_PROJECT_INVESTOR_SUCCESS = 'REMOVE_PROJECT_INVESTOR_SUCCESS';
export const UPDATE_PROJECT_FEE_SUCCESS = 'UPDATE_PROJECT_FEE_SUCCESS';
export const PROJECT_MEATADATA_FAILURE = 'PROJECT_MEATADATA_FAILURE';
export const PROJECT_FEE_FAILURE = 'PROJECT_FEE_FAILURE';
export const PROJECT_NOTES_SUCCESS = 'PROJECT_NOTES_SUCCESS';
export const PROJECT_NOTES_FAILURE = 'PROJECT_NOTES_FAILURE';
export const ADD_NOTE_TO_PROJECT_SUCCESS = 'ADD_NOTE_TO_PROJECT_SUCCESS';
export const ADD_NOTE_TO_PROJECT_FAILURE = 'ADD_NOTE_TO_PROJECT_FAILURE';
export const CANDIDACY_RANK_UPDATE_SUCCESS = 'CANDIDACY_RANK_UPDATE_SUCCESS';
export const PROJECTS_HIDE_FLASH_MESSAGE = 'PROJECTS_HIDE_FLASH_MESSAGE';
export const SAVE_PROJECT_STRATEGY = 'SAVE_PROJECT_STRATEGY';
export const UPDATE_PROJECT_STRATEGY_SUCCESS = 'UPDATE_PROJECT_STRATEGY_SUCCESS';
export const UPDATE_PROJECT_STRATEGY_FAILURE = 'UPDATE_PROJECT_STRATEGY_FAILURE';
export const CHANGE_PROJECTS_VIEW = 'CHANGE_PROJECTS_VIEW';
export const CHANGE_CANDIDACIES_VIEW = 'CHANGE_CANDIDACIES_VIEW';
export const ADD_CANDIDACIES_FAILURE = 'ADD_CANDIDACIES_FAILURE';
export const ADD_CANDIDACIES_SUCCESS = 'ADD_CANDIDACIES_SUCCESS';
export const PROJECT_CATEGORY_SUCCESS = 'PROJECT_CATEGORY_SUCCESS';
export const REQUEST_PROJECT_STRATEGY_SUCCESS = 'REQUEST_PROJECT_STRATEGY_SUCCESS';
export const UPDATE_PROJECT_CLIENT_SUCCESS = 'UPDATE_PROJECT_CLIENT_SUCCESS';
export const PROJECT_SUMMARY_SUCCESS = 'PROJECT_SUMMARY_SUCCESS';
export const PROJECT_SUMMARY_FAILURE = 'PROJECT_SUMMARY_FAILURE';
export const PROJECT_STAT_SUCCESS = 'PROJECT_STAT_SUCCESS';
export const UPDATE_PROJECT_SETTINGS_FAILURE = 'UPDATE_PROJECT_SETTINGS_FAILURE';
export const PROJECT_CANDIDATES_STATS_SUCCESS = 'PROJECT_CANDIDATES_STATS_SUCCESS';
export const CANDIDACY_UPDATE_SUCCESS = 'CANDIDACY_UPDATE_SUCCESS';
export const PROJECT_RECRUITERS_SUCCESS = 'PROJECT_RECRUITERS_SUCCESS';
export const CANDIDACY_OVERVIEW_SUCCESS = 'CANDIDACY_OVERVIEW_SUCCESS';
export const CANDIDACY_OVERVIEW_FAILURE = 'CANDIDACY_OVERVIEW_FAILURE';
export const REORDER_CANDIDACIES_BY_DND = 'REORDER_CANDIDACIES_BY_DND';
export const UPDATE_PROJECT_FIELDS_LIST = 'UPDATE_PROJECT_FIELDS_LIST';
export const OPEN_PROJECT_SETTING = "OPEN_PROJECT_SETTING";
export const HIDE_PROJECT_SETTING = "HIDE_PROJECT_SETTING";
export const CANDIDACIES_FOR_CLOSE_PROJECT_SUCCESS = "CANDIDACIES_FOR_CLOSE_PROJECT_SUCCESS";
export const PROJECTS_AUTOCOMPLETE_SUCCESS = "PROJECTS_AUTOCOMPLETE_SUCCESS";
export const PROJECT_ACTIVITY_SUMMARY_SUCCESS = "PROJECT_ACTIVITY_SUMMARY_SUCCESS";
export const PROJECT_CATEGORY_UPDATE_SUCCESS = "PROJECT_CATEGORY_UPDATE_SUCCESS";
export const PROJECT_CATEGORY_UPDATE_FAILURE = "PROJECT_CATEGORY_UPDATE_FAILURE";
export const UPDATE_PROJECT_ANALYSIS_CARD_SEQUENCE = 'UPDATE_PROJECT_ANALYSIS_CARD_SEQUENCE';

// PEOPLE
export const PERSON_ADD_REQUEST_SUCCESS = 'PERSON_ADD_REQUEST_SUCCESS';
export const PERSON_ADD_REQUEST_FAILURE = 'PERSON_ADD_REQUEST_FAILURE';
export const PEOPLE_LIST_REQUEST = 'PEOPLE_LIST_REQUEST';
export const PEOPLE_LIST_SUCCESS = 'PEOPLE_LIST_SUCCESS';
export const PEOPLE_LIST_FAILURE = 'PEOPLE_LIST_FAILURE';
export const PERSON_DEAL_ADD_SUCCESS = 'PERSON_DEAL_ADD_SUCCESS';
export const PERSON_DEAL_ADD_FAILURE = 'PERSON_DEAL_ADD_FAILURE';
export const PERSON_RELATIONSHIP_ADD_SUCCESS = 'PERSON_RELATIONSHIP_ADD_SUCCESS';
export const PERSON_RELATIONSHIP_ADD_FAILURE = 'PERSON_RELATIONSHIP_ADD_FAILURE';
export const PEOPLE_CHANGE_PAGE_NUMBER = 'PEOPLE_CHANGE_PAGE_NUMBER';
export const PEOPLE_CHANGE_PER_PAGE = 'PEOPLE_CHANGE_PER_PAGE';
export const PEOPLE_CHANGE_SORT_BY = 'PEOPLE_CHANGE_SORT_BY';
export const PEOPLE_HIDE_FLASH_MESSAGE = 'PEOPLE_HIDE_FLASH_MESSAGE';

export const PERSON_CONTACT_INFO_SUCCESS = 'PERSON_CONTACT_INFO_SUCCESS';
export const PERSON_CONTACT_INFO_FAILURE = 'PERSON_CONTACT_INFO_FAILURE';
export const PERSON_NOTES_SUCCESS = 'PERSON_NOTES_SUCCESS';
export const PERSON_NOTES_FAILURE = 'PERSON_NOTES_FAILURE';
export const PERSON_POSITIONS_FAILURE = 'PERSON_POSITIONS_FAILURE';
export const PERSON_POSITIONS_SUCCESS = 'PERSON_POSITIONS_SUCCESS';
export const PERSON_EDUCATIONS_FAILURE = 'PERSON_EDUCATIONS_FAILURE';
export const PERSON_EDUCATIONS_SUCCESS = 'PERSON_EDUCATIONS_SUCCESS';
export const UPDATE_PERSON_POSITIONS_SUCCESS = 'UPDATE_PERSON_POSITIONS_SUCCESS';
export const UPDATE_PERSON_POSITIONS_FAILURE = 'UPDATE_PERSON_POSITIONS_FAILURE';
export const UPDATE_PERSON_POSITIONS = 'UPDATE_PERSON_POSITIONS';
export const UPDATE_PERSON_EDUCATIONS_SUCCESS = 'UPDATE_PERSON_EDUCATIONS_SUCCESS';
export const UPDATE_PERSON_EDUCATIONS_FAILURE = 'UPDATE_PERSON_EDUCATIONS_FAILURE';
export const UPDATE_PERSON_EDUCATIONS = 'UPDATE_PERSON_EDUCATIONS';
export const PERSON_DEALS_FAILURE = 'PERSON_DEALS_FAILURE';
export const PERSON_DEALS_SUCCESS = 'PERSON_DEALS_SUCCESS';
export const PERSON_CANDIDACIES_SUCCESS = 'PERSON_CANDIDACIES_SUCCESS';
export const PERSON_CANDIDACIES_FAILURE = 'PERSON_CANDIDACIES_FAILURE';
export const PERSON_FILES_FAILURE = 'PERSON_FILES_FAILURE';
export const PERSON_FILES_SUCCESS = 'PERSON_FILES_SUCCESS';
export const PERSON_HISTORY_FAILURE = 'PERSON_HISTORY_FAILURE';
export const PERSON_HISTORY_SUCCESS = 'PERSON_HISTORY_SUCCESS';
export const PERSON_RELATIONSHIPS_FAILURE = 'PERSON_RELATIONSHIPS_FAILURE';
export const PERSON_RELATIONSHIPS_SUCCESS = 'PERSON_RELATIONSHIPS_SUCCESS';

export const PERSON_DETAIL_REQUEST = 'PERSON_DETAIL_REQUEST';
export const PERSON_DETAIL_SUCCESS = 'PERSON_DETAIL_SUCCESS';
export const PERSON_DETAIL_FAILURE = 'PERSON_DETAIL_FAILURE';

export const PERSON_RELATIONSHIP_TYPE_SUCCESS = 'PERSON_RELATIONSHIP_TYPE_SUCCESS';
export const IMPORT_CONNECTIONS_SUCCESS = 'IMPORT_CONNECTIONS_SUCCESS';
export const IMPORT_CONNECTIONS_FAILURE = 'IMPORT_CONNECTIONS_FAILURE';
export const PEOPLE_CHANGE_FILTER = 'PEOPLE_CHANGE_FILTER';
export const UPDATE_PERSON_OVERVIEW = 'UPDATE_PERSON_OVERVIEW';
export const UPDATE_PERSON_OVERVIEW_SUCCESS = 'UPDATE_PERSON_OVERVIEW_SUCCESS';
export const UPDATE_PERSON_OVERVIEW_FAILURE = 'UPDATE_PERSON_OVERVIEW_FAILURE';
export const PERSON_RELATIONSHIP_UPDATE_SUCCESS = 'PERSON_RELATIONSHIP_UPDATE_SUCCESS';
export const PERSON_RELATIONSHIP_UPDATE_FAILURE = 'PERSON_RELATIONSHIP_UPDATE_FAILURE';
export const PERSON_RELATIONSHIP_DELETE_SUCCESS = 'PERSON_RELATIONSHIP_DELETE_SUCCESS';
export const PERSON_RELATIONSHIP_DELETE_FAILURE = 'PERSON_RELATIONSHIP_DELETE_FAILURE';
export const ADD_TO_PROJECT_SUCCESS = 'ADD_TO_PROJECT_SUCCESS';
export const ADD_TO_PROJECT_FAILURE = 'ADD_TO_PROJECT_FAILURE';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE';
export const MERGE_PEOPLE_SUCCESS = 'MERGE_PEOPLE_SUCCESS';
export const MERGE_PEOPLE_FAILURE = 'MERGE_PEOPLE_FAILURE';
export const ADD_TAGS_SUCCESS = 'ADD_TAGS_SUCCESS';
export const ADD_TAGS_FAILURE = 'ADD_TAGS_FAILURE';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const UPDATE_PERSON_FAILURE = 'UPDATE_PERSON_FAILURE';
export const PEOPLE_EXPORT_SUCCESS = 'PEOPLE_EXPORT_SUCCESS';
export const ADD_NOTE_TO_PERSON_SUCCESS = 'ADD_NOTE_TO_PERSON_SUCCESS';
export const ADD_NOTE_TO_PERSON_FAILURE = 'ADD_NOTE_TO_PERSON_FAILURE';
export const PERSON_FILE_UPLOAD_SUCCESS = 'PERSON_FILE_UPLOAD_SUCCESS';
export const CHANGE_PEOPLE_VIEW = 'CHANGE_PEOPLE_VIEW';
export const PERSON_COMPENSATION_SUCCESS = 'PERSON_COMPENSATION_SUCCESS';
export const IMPORT_PERSON_CONTACT_SUCCESS = 'IMPORT_PERSON_CONTACT_SUCCESS';
export const IMPORT_PERSON_CONTACT_FAILURE = 'IMPORT_PERSON_CONTACT_FAILURE';
export const PERSON_AUTOCOMPLETE_SUCCESS = 'PERSON_AUTOCOMPLETE_SUCCESS';
export const PERSON_CANDIDACIES_UPDATE_SUCCESS = 'PERSON_CANDIDACIES_UPDATE_SUCCESS';
export const PERSON_CANDIDACIES_UPDATE_FAILURE = 'PERSON_CANDIDACIES_UPDATE_FAILURE';
export const OPEN_DEALS_AND_PROJECTS_SUCCESS = 'OPEN_DEALS_AND_PROJECTS_SUCCESS';
export const OPEN_DEALS_AND_PROJECTS_FAILURE = 'OPEN_DEALS_AND_PROJECTS_FAILURE';
export const GENERATE_PERSON_REPORT_SUCCESS = 'GENERATE_PERSON_REPORT_SUCCESS';
export const GENERATE_PERSON_REPORT_FAILURE = 'GENERATE_PERSON_REPORT_FAILURE';
export const CLOSE_NOTIFICATION_POPUP = 'CLOSE_NOTIFICATION_POPUP';
export const PROJECT_HIDE_FLASH_MESSAGE = 'PROJECT_HIDE_FLASH_MESSAGE';
export const PROJECT_CANDIDACY_COMPANIES_SUCCESS = "PROJECT_CANDIDACY_COMPANIES_SUCCESS";
export const PEOPLE_TAGS_SUCCESS = "PEOPLE_TAGS_SUCCESS";
export const PEOPLE_TAGS_FAILURE = "PEOPLE_TAGS_FAILURE";
export const UPDATE_PERSON_FIELDS_LIST = "UPDATE_PERSON_FIELDS_LIST";
export const ADD_PERSON_TO_PROJECT_SUCCESS = "ADD_PERSON_TO_PROJECT_SUCCESS";
export const ADD_PERSON_TO_PROJECT_FAILURE = "ADD_PERSON_TO_PROJECT_FAILURE";
export const PEOPLE_PARSE_RESUME_SUCCESS = "PEOPLE_PARSE_RESUME_SUCCESS";
export const PEOPLE_PARSE_RESUME_FAILURE = "PEOPLE_PARSE_RESUME_FAILURE";

//Companies
export const COMPANY_LIST_REQUEST = 'COMPANY_LIST_REQUEST';
export const COMPANY_LIST_SUCCESS = 'COMPANY_LIST_SUCCESS';
export const COMPANY_LIST_FAILURE = 'COMPANY_LIST_FAILURE';
export const COMPANY_CHANGE_PAGE_NUMBER = 'COMPANY_CHANGE_PAGE_NUMBER';
export const COMPANY_CHANGE_PER_PAGE = 'COMPANY_CHANGE_PER_PAGE';
export const COMPANY_CHANGE_SORT_BY = 'COMPANY_CHANGE_SORT_BY';
export const COMPANY_CHANGE_FILTER = 'COMPANY_CHANGE_FILTER';
export const COMPANY_DETAIL_REQUEST = 'COMPANY_DETAIL_REQUEST';
export const COMPANY_DETAIL_SUCCESS = 'COMPANY_DETAIL_SUCCESS';
export const COMPANY_CONTACT_INFO_SUCCESS = 'COMPANY_CONTACT_INFO_SUCCESS';
export const COMPANY_CONTACT_INFO_FAILURE = 'COMPANY_CONTACT_INFO_FAILURE';
export const COMPANY_NOTES_SUCCESS = 'COMPANY_NOTES_SUCCESS';
export const COMPANY_NOTES_FAILURE = 'COMPANY_NOTES_FAILURE';
export const COMPANY_DEALS_FAILURE = 'COMPANY_DEALS_FAILURE';
export const COMPANY_DEALS_SUCCESS = 'COMPANY_DEALS_SUCCESS';
export const COMPANY_PROJECTS_FAILURE = 'COMPANY_PROJECTS_FAILURE';
export const COMPANY_PROJECTS_SUCCESS = 'COMPANY_PROJECTS_SUCCESS';
export const COMPANY_RELATIONSHIPS_FAILURE = 'COMPANY_RELATIONSHIPS_FAILURE';
export const COMPANY_RELATIONSHIPS_SUCCESS = 'COMPANY_RELATIONSHIPS_SUCCESS';
export const COMPANY_RELATIONSHIP_ADD_SUCCESS = 'COMPANY_RELATIONSHIP_ADD_SUCCESS';
export const COMPANY_RELATIONSHIP_ADD_FAILURE = 'COMPANY_RELATIONSHIP_ADD_FAILURE';
export const SEARCH_COMPANY_LIST = 'SEARCH_COMPANY_LIST';
export const COMPANY_LIST_RESET = 'COMPANY_LIST_RESET';
export const COMPANY_RELATIONSHIP_DELETE_SUCCESS = 'COMPANY_RELATIONSHIP_DELETE_SUCCESS';
export const COMPANY_RELATIONSHIP_DELETE_FAILURE = 'COMPANY_RELATIONSHIP_DELETE_FAILURE';
export const UPDATE_COMPANY_CONTACT_INFO = 'UPDATE_COMPANY_CONTACT_INFO';
export const UPDATE_COMPANY_CONTACT_INFO_SUCCESS = 'UPDATE_COMPANY_CONTACT_INFO_SUCCESS';
export const UPDATE_COMPANY_CONTACT_INFO_FAILURE = 'UPDATE_COMPANY_CONTACT_INFO_FAILURE';
export const COMPANY_RELATIONSHIP_UPDATE_SUCCESS = 'COMPANY_RELATIONSHIP_UPDATE_SUCCESS';
export const COMPANY_RELATIONSHIP_UPDATE_FAILURE = 'COMPANY_RELATIONSHIP_UPDATE_FAILURE';
export const MERGE_COMPANIES_SUCCESS = 'MERGE_COMPANIES_SUCCESS';
export const MERGE_COMPANIES_FAILURE = 'MERGE_COMPANIES_FAILURE';
export const ADD_TAGS_TO_COMPANY_SUCCESS = 'ADD_TAGS_TO_COMPANY_SUCCESS';
export const ADD_TAGS_TO_COMPANY_FAILURE = 'ADD_TAGS_TO_COMPANY_FAILURE';
export const COMPANIES_HIDE_FLASH_MESSAGE = 'COMPANIES_HIDE_FLASH_MESSAGE';

export const ADD_NOTE_TO_COMPANY_SUCCESS = 'ADD_NOTE_TO_COMPANY_SUCCESS';
export const ADD_NOTE_TO_COMPANY_FAILURE = 'ADD_NOTE_TO_COMPANY_FAILURE';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE';

export const COMPANY_ADD_REQUEST_SUCCESS = 'COMPANY_ADD_REQUEST_SUCCESS';
export const COMPANY_ADD_REQUEST_FAILURE = 'COMPANY_ADD_REQUEST_FAILURE';
export const CHANGE_COMPANY_VIEW = 'CHANGE_COMPANY_VIEW';
export const COMPANIES_TAGS_SUCCESS = 'COMPANIES_TAGS_SUCCESS';
export const COMPANIES_TAGS_FAILURE = 'COMPANIES_TAGS_FAILURE';
export const UPDATE_COMPANY_FIELDS_LIST = 'UPDATE_COMPANY_FIELDS_LIST';
export const COMPANY_RECENT_PROJECT_DATA_SUCCESS = 'COMPANY_RECENT_PROJECT_DATA_SUCCESS';
export const COMPANY_RECENT_PROJECT_DATA_FAILURE = 'COMPANY_RECENT_PROJECT_DATA_FAILURE';

// Deals
export const DEAL_ADD_REQUEST_SUCCESS = 'DEAL_ADD_REQUEST_SUCCESS';
export const DEAL_ADD_REQUEST_FAILURE = 'DEAL_ADD_REQUEST_FAILURE';
export const DEAL_LIST_REQUEST = 'DEAL_LIST_REQUEST';
export const DEAL_LIST_SUCCESS = 'DEAL_LIST_SUCCESS';
export const DEAL_LIST_FAILURE = 'DEAL_LIST_FAILURE';
export const DEAL_CHANGE_PAGE_NUMBER = 'DEAL_CHANGE_PAGE_NUMBER';
export const DEAL_CHANGE_SORT_BY = 'DEAL_CHANGE_SORT_BY';
export const DEAL_CHANGE_FILTER = 'DEAL_CHANGE_FILTER';
export const DEAL_DETAIL_REQUEST = 'DEAL_DETAIL_REQUEST';
export const DEAL_DETAIL_SUCCESS = 'DEAL_DETAIL_SUCCESS';
export const DEAL_BULK_STATUS_UPDATE_SUCCESS = 'DEAL_BULK_STATUS_UPDATE_SUCCESS';
export const DEAL_ACTIVITY_LIST_SUCCESS = 'DEAL_ACTIVITY_LIST_SUCCESS';
export const DEAL_ACTIVITY_LIST_FAILURE = 'DEAL_ACTIVITY_LIST_FAILURE';
export const ADD_NOTE_TO_DEAL_SUCCESS = 'ADD_NOTE_TO_DEAL_SUCCESS';
export const ADD_NOTE_TO_DEAL_FAILURE = 'ADD_NOTE_TO_DEAL_FAILURE';
export const DEAL_NOTES_SUCCESS = 'DEAL_NOTES_SUCCESS';
export const DEAL_NOTES_FAILURE = 'DEAL_NOTES_FAILURE';
export const UPDATE_DEAL_DETAILS_SUCCESS = 'UPDATE_DEAL_DETAILS_SUCCESS';
export const UPDATE_DEAL_DETAILS_FAILURE = 'UPDATE_DEAL_DETAILS_FAILURE';
export const DEALS_EXPORT_SUCCESS = 'DEALS_EXPORT_SUCCESS';
export const DEAL_BULK_NOTE_ADD_SUCCESS = 'DEAL_BULK_NOTE_ADD_SUCCESS';
export const REQUEST_DEAL_STATUSES = 'REQUEST_DEAL_STATUSES';
export const REQUEST_DEAL_STATES = 'REQUEST_DEAL_STATES';
export const DEALS_BULK_TAG_ADD_SUCCESS = 'DEALS_BULK_TAG_ADD_SUCCESS';
export const DEALS_BULK_TAG_ADD_FAILURE = 'DEALS_BULK_TAG_ADD_FAILURE';
export const DEALS_HIDE_FLASH_MESSAGE = 'DEALS_HIDE_FLASH_MESSAGE';
export const CHANGE_DEALS_VIEW = 'CHANGE_DEALS_VIEW';
export const DEALS_DELETE_SUCCESS = 'DEALS_DELETE_SUCCESS';
export const DEAL_TAGS_SUCCESS = 'DEAL_TAGS_SUCCESS';
export const UPDATE_DEALS_FIELDS_LIST = "UPDATE_DEALS_FIELDS_LIST";

//Static Data

export const USER_INTERESTS_SUCCESS = "USER_INTERESTS";
export const USER_INTERESTS_FAILURE = "USER_INTERESTS_FAILURE";
export const USER_REFS_SUCCESS = "USER_REFS_SUCCESS";
export const USER_REFS_FAILURE = "USER_REFS_FAILURE";

//tags
export const TAGS_CHANGE_PAGE_NUMBER = 'TAGS_CHANGE_PAGE_NUMBER';
export const REQUEST_TAG_LIST = 'REQUEST_TAG_LIST';
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_FAILURE = 'CREATE_TAG_FAILURE';
export const TAG_ADD_REQUEST_SUCCESS = 'TAG_ADD_REQUEST_SUCCESS';
export const TAG_ADD_REQUEST_FAILURE = 'TAG_ADD_REQUEST_FAILURE';
export const TAG_DELETE_REQUEST_SUCCESS = 'TAG_DELETE_REQUEST_SUCCESS';
export const TAG_DELETE_REQUEST_FAILURE = 'TAG_DELETE_REQUEST_FAILURE';
export const REQUEST_MANAGE_TAG = 'REQUEST_MANAGE_TAG';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILURE = 'UPDATE_TAG_FAILURE';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';
export const TAG_SORT_BY_NAME = 'TAG_SORT_BY_NAME';
export const TAG_LIST_FILTER = 'TAG_LIST_FILTER';
export const TAG_DOWNLOAD_SUCCESS = 'TAG_DOWNLOAD_SUCCESS';
export const TAG_HIDE_FLASH_MESSAGE = 'TAG_HIDE_FLASH_MESSAGE';
export const TAG_OBJECTS_SUCCESS = 'TAG_OBJECTS_SUCCESS';

// tasks
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_ASSIGNEES_LIST_SUCCESS = 'TASK_ASSIGNEES_LIST_SUCCESS';
export const TASK_ADD_REQUEST_SUCCESS = 'TASK_ADD_REQUEST_SUCCESS';
export const TASK_ADD_REQUEST_FAILURE = 'TASK_ADD_REQUEST_FAILURE';
export const TASK_CHANGE_BY_FILTER = 'TASK_CHANGE_BY_FILTER';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const TASK_DETAIL_SUCCESS = 'TASK_DETAIL_SUCCESS';
export const REQUEST_MY_TASK = 'REQUEST_MY_TASK';
export const MARK_TASK_AS_DONE_SUCCESS = 'MARK_TASK_AS_DONE_SUCCESS';
export const REQUEST_PROJECT_TASK = 'REQUEST_PROJECT_TASK';
export const PROJECT_TASK_LIST_SUCCESS = 'PROJECT_TASK_LIST_SUCCESS';
export const PROJECT_TASK_CHANGE_BY_FILTER = 'PROJECT_TASK_CHANGE_BY_FILTER';
export const TASK_UPDATE_REQUEST_SUCCESS = 'TASK_UPDATE_REQUEST_SUCCESS';
export const TASK_UPDATE_REQUEST_FAILURE = 'TASK_UPDATE_REQUEST_FAILURE';
export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const OUTSTANDING_TASKS_SUCCESS = 'OUTSTANDING_TASKS_SUCCESS';
export const DELETE_PROJECT_TASK_SUCCESS = "DELETE_PROJECT_TASK_SUCCESS";

//dashboard
export const DASHBOARD_CLOSED_PROJECTS_STATS_SUCCESS = 'DASHBOARD_CLOSED_PROJECTS_STATS_SUCCESS';
export const DASHBOARD_PLACEMENT_DAYS_STATS_SUCCESS = 'DASHBOARD_PLACEMENT_DAYS_STATS_SUCCESS';
export const DASHBOARD_RECENT_REPORT_SUCCESS = 'DASHBOARD_RECENT_REPORT_SUCCESS';
export const DASHBOARD_ACTIVE_PROJECTS_STATS_SUCCESS = 'DASHBOARD_ACTIVE_PROJECTS_STATS_SUCCESS';
export const DASHBOARD_RECENT_PEOPLE_SUCCESS = 'DASHBOARD_RECENT_PEOPLE_SUCCESS';
export const DASHBOARD_TASKS_SUCCESS = 'DASHBOARD_TASKS_SUCCESS';
export const DASHBOARD_DEALS_SUCCESS = 'DASHBOARD_DEALS_SUCCESS';
export const DASHBOARD_STATS_SUCCESS = 'DASHBOARD_STATS_SUCCESS';
export const DASHBOARD_ACTIVITIES_SUCCESS = 'DASHBOARD_ACTIVITIES_SUCCESS';
export const DASHBOARD_MY_PROJECTS_SUCCESS = 'DASHBOARD_MY_PROJECTS_SUCCESS';
export const DASHBOARD_RECENT_PROJECTS_SUCCESS = 'DASHBOARD_RECENT_PROJECTS_SUCCESS';
export const DASHBOARD_CLOSED_PROJECTS_SUCCESS = 'DASHBOARD_CLOSED_PROJECTS_SUCCESS';
export const ACCOUNT_DASHBOARD_ACTIVE_PROJECTS_STATS_SUCCESS = 'ACCOUNT_DASHBOARD_ACTIVE_PROJECTS_STATS_SUCCESS';
export const ACCOUNT_DASHBOARD_MY_PROJECTS_SUCCESS = 'ACCOUNT_DASHBOARD_MY_PROJECTS_SUCCESS';
export const ACCOUNT_DASHBOARD_CLOSED_PROJECTS_SUCCESS = 'ACCOUNT_DASHBOARD_CLOSED_PROJECTS_SUCCESS';
export const ACCOUNT_DASHBOARD_CLOSED_PROJECTS_STATS_SUCCESS = 'ACCOUNT_DASHBOARD_CLOSED_PROJECTS_STATS_SUCCESS';
export const ACCOUNT_DASHBOARD_PLACEMENT_DAYS_STATS_SUCCESS = 'ACCOUNT_DASHBOARD_PLACEMENT_DAYS_STATS_SUCCESS';
export const UPDATE_DASHBOARD_CARD_SEQUENCE = "UPDATE_DASHBOARD_CARD_SEQUENCE";

// users
export const ACTIVE_USERS_LIST_SUCCESS = 'ACTIVE_USERS_LIST_SUCCESS';
export const SHOW_USER_DETAIL_SUCCESS = 'SHOW_USER_DETAIL_SUCCESS';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_FAILURE = 'SETUP_USER_FAILURE';
export const ACTIVATE_USER_REQUEST_SUCCESS = 'ACTIVATE_USER_REQUEST_SUCCESS';
export const ACTIVATE_USER_REQUEST_FAILURE = 'ACTIVATE_USER_REQUEST_FAILURE';
export const USER_CHANGE_PER_PAGE = 'USER_CHANGE_PER_PAGE';
export const USER_CHANGE_PAGE_NUMBER = 'USER_CHANGE_PAGE_NUMBER';
export const USER_RELATED_PROJECTS_SUCCESS = 'USER_RELATED_PROJECTS_SUCCESS';
export const USER_RELATED_PROJECTS_FAILURE = 'USER_RELATED_PROJECTS_FAILURE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
export const USERS_CHANGE_SORT_BY = 'USERS_CHANGE_SORT_BY';
export const BULK_USER_ACTIONS = 'BULK_USER_ACTIONS';
export const BULK_USER_DELETE_ACTION_SUCCESS = 'BULK_USER_DELETE_ACTION_SUCCESS';
export const BULK_USER_ACTIONS_SUCCESS = 'BULK_USER_ACTIONS_SUCCESS';
export const BULK_USER_ACTIONS_FAILURE = 'BULK_USER_ACTIONS_FAILURE';
export const LIST_USER_ROLES = 'LIST_USER_ROLES';
export const REQUEST_USER_UPDATE = 'REQUEST_USER_UPDATE';
export const USER_LIST_FILTER = 'USER_LIST_FILTER';
export const REQUEST_MFA_CODE_SUCCESS = 'REQUEST_MFA_CODE_SUCCESS';
export const REQUEST_MFA_CODE_FAILURE = 'REQUEST_MFA_CODE_FAILURE';
export const MFA_CODE_VERIFY_SUCCESS = 'MFA_CODE_VERIFY_SUCCESS';
export const MFA_CODE_VERIFY_FAILURE = 'MFA_CODE_VERIFY_FAILURE';
export const HIDE_MFA_FLASH_MESSAGE = 'HIDE_MFA_FLASH_MESSAGE';

// attachments
export const DELETE_ATTACHMENT_SUCCESS = 'DELETE_ATTACHMENT_SUCCESS';
// candidacies
export const REMOVE_CANDIDACY_SUCCESS = 'REMOVE_CANDIDACY_SUCCESS';
export const CANDIDACY_NOTES_SUCCESS = 'CANDIDACY_NOTES_SUCCESS';
export const CANDIDACY_NOTES_FAILURE = 'CANDIDACY_NOTES_FAILURE';
export const CANDIDACY_DETAIL_REQUEST = 'CANDIDACY_DETAIL_REQUEST';
export const CANDIDACY_DETAIL_FAILURE = 'CANDIDACY_DETAIL_FAILURE';
export const CANDIDACY_DETAIL_SUCCESS = 'CANDIDACY_DETAIL_SUCCESS';
export const ADD_NOTE_TO_CANDIDACY_SUCCESS = 'ADD_NOTE_TO_CANDIDACY_SUCCESS';
export const ADD_NOTE_TO_CANDIDACY_FAILURE = 'ADD_NOTE_TO_CANDIDACY_FAILURE';
export const CHANGE_CANDIDACIES_CLIENT_VIEW = 'CHANGE_CANDIDACIES_CLIENT_VIEW';
export const UPDATE_CANDIDACIES_FIELDS_LIST = "UPDATE_CANDIDACIES_FIELDS_LIST";

//Notes
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAILURE = 'UPDATE_NOTE_FAILURE';
export const GET_FILEIN_OPTIONS_SUCCESS = 'GET_FILEIN_OPTIONS_SUCCESS';
export const GET_FILEIN_OPTIONS_FAILURE = 'GET_FILEIN_OPTIONS_FAILURE';

// firms
export const FIRM_USER_LIST_SUCCESS = 'FIRM_USER_LIST_SUCCESS';
export const FIRM_USER_LIST_FAILURE = 'FIRM_USER_LIST_FAILURE';
export const FIRM_USER_LIST_REQUEST = 'FIRM_USER_LIST_REQUEST';
export const FIRM_DETAILS_SUCCESS = 'FIRM_DETAILS_SUCCESS';
export const FIRM_DETAILS_FAILURE = 'FIRM_DETAILS_FAILURE';
export const UPDATE_FIRM_INFO = 'UPDATE_FIRM_INFO';
export const UPDATE_FIRM_INFO_SUCCESS = 'UPDATE_FIRM_INFO_SUCCESS';
export const UPDATE_FIRM_INFO_FAILURE = 'UPDATE_FIRM_INFO_FAILURE';
export const FIRM_HIDE_FLASH_MESSAGE = 'FIRM_HIDE_FLASH_MESSAGE';
export const ADD_NEW_FIRM_USER = 'ADD_NEW_FIRM_USER';
export const ADD_NEW_FIRM_USER_SUCCESS = 'ADD_NEW_FIRM_USER_SUCCESS';
export const ADD_NEW_FIRM_USER_FAILURE = 'ADD_NEW_FIRM_USER_FAILURE';
export const FIRM_LIST_FOR_CURRENT_ACCOUNT_SUCCESS = 'FIRM_LIST_FOR_CURRENT_ACCOUNT_SUCCESS';
export const FIRM_FEATURE_SUCCESS = 'FIRM_FEATURE_SUCCESS';
export const FIRM_FEATURE_FAILURE = 'FIRM_FEATURE_FAILURE';

// recent visited entity
export const RECENT_VISITED_ENTITIES_LIST_SUCCESS = 'RECENT_VISITED_ENTITIES_LIST_SUCCESS';
export const ADD_RECENT_VISITED_ENTITY_SUCCESS = 'ADD_RECENT_VISITED_ENTITY_SUCCESS';

// firmCategories
export const FIRM_CATEGORY_CREATE_SUCCESS = 'FIRM_CATEGORY_CREATE_SUCCESS';
export const FIRM_CATEGORY_CREATE_FAILURE = 'FIRM_CATEGORY_CREATE_FAILURE';
export const FIRM_CATEGORY_UPDATE_SUCCESS = 'FIRM_CATEGORY_UPDATE_SUCCESS';
export const FIRM_CATEGORY_UPDATE_FAILURE = 'FIRM_CATEGORY_UPDATE_FAILURE';

//account
export const ACCOUNT_UPDATE_SUCCESS = 'ACCOUNT_UPDATE_SUCCESS';
export const ACCOUNT_UPDATE_FAILURE = 'ACCOUNT_UPDATE_FAILURE';

// Overview Notes
export const UPDATE_CANDIDATE_OVERVIEW_FAILURE = 'UPDATE_CANDIDATE_OVERVIEW_FAILURE';
export const UPDATE_CANDIDATE_OVERVIEW_SUCCESS = 'UPDATE_CANDIDATE_OVERVIEW_SUCCESS';


export const HEADER_TRANSPERENCY = "HEADER_TRANSPERENCY";
