development:
  adapter: mysql2
  encoding: unicode
  reconnect: false
  host: localhost
  database: reit_simple_dev
  user: root
  password: 

test:
  adapter: mysql2
  encoding: unicode
  reconnect: false
  host: localhost
  database: reit_simple_test
  user: root
  password: 